#!/usr/bin/env bash

home="$(realpath "$(realpath "${BASH_SOURCE[0]}" | xargs dirname)"/.)"
cd "$home"

# "$home"/node_modules/.bin/nodexh --require=./lib/cli.js "$@"
# #!/usr/local/bin/node --trace-deprecation
# "$home"/node_modules/.bin/nodexh -p "require('./lib/cli.js');" "$@"
./node_modules/.bin/nodexh ./lib/cli.js "$@"

