#!/usr/bin/env bash
set -euo pipefail

home="$(realpath "$(realpath "${BASH_SOURCE[0]}" | xargs dirname)"/.)"
cd "$home"

browserify -r mudom     -o app/static/browserified/mudom.js
# browserify -r combokeys --standalone Combokeys -o app/static/browserified/combokeys.js
browserify -r combokeys -o app/static/browserified/combokeys.js

